/* eslint-disable jsx-a11y/alt-text */
/* eslint-disable react-hooks/exhaustive-deps */

import { Grid, IconButton } from "@mui/material";
import Head from "next/head";
import { useRouter } from "next/router";
import * as React from "react";
import { connect } from "react-redux";
import { tokenActions } from "../../../redux/actions";
import _ from "lodash";
import { FaDiscord, FaFacebook, FaTelegram, FaTwitter } from "react-icons/fa";

import AdminProductCard from "../../Cards/AdminProductCard";
import { SolidButton } from "../../Buttons";

function Originals(props: any) {
  const router = useRouter();
  const sliderRef = React.useRef();
  const [emptyAdminTokens, setEmptyAdminTokens] = React.useState(false);

  React.useEffect(() => {
    props.getAllAdmin();
  }, [props.getAll]);

  const socialIcons = [
    {
      icon: FaDiscord,
      href: "#",
    },
    {
      icon: FaTelegram,
      href: "#",
    },
    {
      icon: FaTwitter,
      href: "#",
    },
    {
      icon: FaFacebook,
      href: "#",
    },
  ];

  const { loading, adminTokens } = props;

  return (
    <div className="">
      <Head>
        <title>100NFT Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <meta property="og:url" content="www.100pcotton.com" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="100Percent Cotton" />
        <meta property="twitter:card" content="summary" />
        <meta
          property="og:description"
          content="Home for Awesome T-shirts and NFTs"
        />
        <meta
          property="og:image"
          content={
            "https://res.cloudinary.com/z-pro-trading/image/upload/w_1000,ar_16:9,c_fill,g_auto,e_sharpen/v1662043315/assets/preview_ubvavg.png"
          }
        />
      </Head>

      <main className="">
        <div className="mt-4 mb-12 p-0 flex flex-col md:flex-row justify-center items-start gap-4 h-full">
          <div className="w-full h-full md:h-[250px] md:w-8/12 bg-[#fafafa] shadow-paper rounded-[2em] md:rounded-[1em]  mt-0 mb-[1.5em] md:mb-0">
            <div className="flex flex-row gap-4 justify-between w-full py-4 px-8">
              <Grid item xs={7} style={{ paddingTop: "0" }}>
                <div className="flex justify-start items-center gap-2 font-bold text-[24px] my-2">
                  <div className="gradient-text bg-gradient-to-r from-[#A01AEC] via-[#CB527D] to-[#DF9361] bg-clip-text fill-transparent">
                    Original Tokens
                  </div>
                </div>
                <div className="text-[13px] text-[#707070] font-light mb-3  ">
                  Be one onf the lucky few tok grab a copy of these and earn for
                  a lifetime{" "}
                </div>
                {/* <button
                    className="text-center font-medium border-none text-[#fafafa] bg-gradient-to-b from-[#E25822] via-[#D94D22] to-[#B22222] text-[0.875em] rounded-[3em] px-[2em] py-[0.2em]"
                    onClick={handleSpin}>
                    Spin here
                  </button> */}
              </Grid>
            </div>
          </div>

          <div className="w-full h-fit md:h-[250px] md:w-4/12 md:px-4">
            <div className="h-full text-[#ec4352] text-center p-2 mb-2 rounded-3xl shadow-paper bg-[#fafafa]">
              <div className="font-bold text-[24px] gradient-text bg-gradient-to-tl from-[#A01AEC] via-[#CB527D] to-[#DF9361] bg-clip-text fill-transparent mb-3">
                Browse Here
              </div>
              <div className="text-[12px] text-textGray font-light text-center mb-4">
                Click below to browse other categories of designs
              </div>

              {/* <button
                    className="text-center font-medium border-none text-[#fafafa] bg-gradient-to-b from-[#E25822] via-[#D94D22] to-[#B22222] text-[0.875em] rounded-[3em] px-[2em] py-[0.2em]"
                    onClick={() => router.push("/dashboard/help")}
                    disabled={emptyAdminTokens}>
                    See help
                  </button> */}
              <div className="w-full mx-auto flex justify-center">
                <SolidButton onClick={() => router.push("/dashboard")}>
                  Browse Here
                </SolidButton>
              </div>
            </div>
          </div>
        </div>

        {!loading && !adminTokens?.length && (
          <div className="w-full h-full flex flex-col justify-center items-center">
            <div className="text-[#b22222] p-2 mb-2 rounded-3xl shadow-paper bg-[#fff] text-center">
              <p className="text-[#121212] text-[1.1em] font-bold">
                Looks like all our original tokens have been minted. Please
                follow our socials for the next drop.
              </p>
              <div>
                {socialIcons.map((icon, i) => (
                  <IconButton
                    key={i}
                    onClick={() => window.open("#", "_blank")}>
                    <icon.icon />
                  </IconButton>
                ))}
              </div>
            </div>
          </div>
        )}

        {loading && (
          <div className="bg-[#fafafa] shadow-paper rounded-[1.8em] my-4 p-8">
            <div className="w-full grid grid-cols-2 md:grid-cols-4 gap-4 my-1">
              <div className="bg-transparent h-72 rounded-full my-4 animate-pulse flex flex-col gap-4 ">
                <div className="h-5/6 bg-skeleton rounded-[1.5em]"></div>
                <div className="h-1/6 bg-skeleton rounded-[1.5em]"></div>
              </div>
              <div className="bg-transparent h-72 rounded-full my-4 animate-pulse flex flex-col gap-3 ">
                <div className="h-5/6 bg-skeleton rounded-[1.5em]"></div>
                <div className="h-1/6 bg-skeleton rounded-[1.5em]"></div>
              </div>
              <div className="bg-transparent h-72 rounded-full my-4 animate-pulse flex flex-col gap-3 ">
                <div className="h-5/6 bg-skeleton rounded-[1.5em]"></div>
                <div className="h-1/6 bg-skeleton rounded-[1.5em]"></div>
              </div>
              <div className="bg-transparent h-72 rounded-full my-4 animate-pulse flex flex-col gap-3 ">
                <div className="h-5/6 bg-skeleton rounded-[1.5em]"></div>
                <div className="h-1/6 bg-skeleton rounded-[1.5em]"></div>
              </div>
            </div>
          </div>
        )}

        {!loading && adminTokens?.length > 0 && true && (
          <div className="rounded-[2em] p-4 md:p-8 my-4 shadow-paper bg-[#fff]">
            <div className="grid grid-cols-2 md:grid-cols-4 justify-start gap-8 w-full">
              {adminTokens?.length > 0 &&
                _.filter(adminTokens, "isOriginal")?.map(
                  (value: any, i: React.Key | null | undefined) => (
                    <div key={i} className="w-full h-full">
                      <AdminProductCard token={value} />
                    </div>
                  )
                )}
            </div>
          </div>
        )}
      </main>
    </div>
  );
}

function mapState(state: {
  token: {
    adminTokens: any;
    proposedTokens: any;
    loading: any;
    originalTokens: any;
  };
}) {
  const { adminTokens, proposedTokens, loading, originalTokens } = state.token;
  return { proposedTokens, loading, originalTokens, adminTokens };
}

const actionCreators = {
  getAllAdmin: tokenActions.getAllAdmin,
  getProposed: tokenActions.getProposed,
};

const ConnectedOriginalsPage = connect(mapState, actionCreators)(Originals);
export default ConnectedOriginalsPage;
