export const auctionConstants = {
    GETALL_AUCTION_REQUEST: 'GETALL_AUCTION_REQUEST',
    GETALL_AUCTION_SUCCESS: 'GETALL_AUCTION_SUCCESS',
    GETALL_AUCTION_FAILURE: 'GETALL_AUCTION_FAILURE',

    GETSINGLE_AUCTION_REQUEST: 'GETSINGLE_AUCTION_REQUEST',
    GETSINGLE_AUCTION_SUCCESS: 'GETSINGLE_AUCTION_SUCCESS',
    GETSINGLE_AUCTION_FAILURE: 'GETSINGLE_AUCTION_FAILURE',

    GETBIDS_AUCTION_REQUEST: 'GETBIDS_AUCTION_REQUEST',
    GETBIDS_AUCTION_SUCCESS: 'GETBIDS_AUCTION_SUCCESS',
    GETBIDS_AUCTION_FAILURE: 'GETBIDS_AUCTION_FAILURE',

    GET_SINGLE_BID_REQUEST: 'GET_SINGLE_BID_REQUEST',
    GET_SINGLE_BID_SUCCESS: 'GET_SINGLE_BID_SUCCESS',
    GET_SINGLE_BID_FAILURE: 'GET_SINGLE_BID_FAILURE',

    GETAUCTION_BIDS_REQUEST: 'GETAUCTION_BIDS_REQUEST',
    GETAUCTION_BIDS_SUCCESS: 'GETAUCTION_BIDS_SUCCESS',
    GETAUCTION_BIDS_FAILURE: 'GETAUCTION_BIDS_FAILURE',

    CREATE_AUCTION_REQUEST: 'CREATE_AUCTION_REQUEST',
    CREATE_AUCTION_SUCCESS: 'CREATE_AUCTION_SUCCESS',
    CREATE_AUCTION_FAILURE: 'CREATE_AUCTION_FAILURE',

    PLACEBID_AUCTION_REQUEST: 'PLACEBID_AUCTION_REQUEST',
    PLACEBID_AUCTION_SUCCESS: 'PLACEBID_AUCTION_SUCCESS',
    PLACEBID_AUCTION_FAILURE: 'PLACEBID_AUCTION_FAILURE',

    SEND_BIDWINNER_MAIL_REQUEST: 'SEND_BIDWINNER_MAIL_REQUEST',
    SEND_BIDWINNER_MAIL_SUCCESS: 'SEND_BIDWINNER_MAIL_SUCCESS',
    SEND_BIDWINNER_MAIL_FAILURE: 'SEND_BIDWINNER_MAIL_FAILURE',

    SEND_BIDWINNER_O_MAIL_REQUEST: 'SEND_BIDWINNER_O_MAIL_REQUEST',
    SEND_BIDWINNER_O_MAIL_SUCCESS: 'SEND_BIDWINNER_O_MAIL_SUCCESS',
    SEND_BIDWINNER_O_MAIL_FAILURE: 'SEND_BIDWINNER_O_MAIL_FAILURE',

    COlLECT_TOKEN_HASH_REQUEST: 'COlLECT_TOKEN_HASH_REQUEST',
    COLLECT_TOKEN_HASH_SUCCESS: 'COLLECT_TOKEN_HASH_SUCCESS',
    COLLECT_TOKEN_HASH_FAILURE: 'COLLECT_TOKEN_HASH_FAILURE',



    DELETE_AUCTION_REQUEST: 'DELETE_AUCTION_REQUEST',
    DELETE_AUCTION_SUCCESS: 'DELETE_AUCTION_SUCCESS',
    DELETE_AUCTION_FAILURE: 'DELETE_AUCTION_FAILURE',

};
