export const orderConstants = {
  GETALL_ORDER_REQUEST: "GETALL_ORDER_REQUEST",
  GETALL_ORDER_SUCCESS: "GETALL_ORDER_SUCCESS",
  GETALL_ORDER_FAILURE: "GETALL_ORDER_FAILURE",

  GETALL_TX_REQUEST: "GETALL_TX_REQUEST",
  GETALL_TX_SUCCESS: "GETALL_TX_SUCCESS",
  GETALL_TX_FAILURE: "GETALL_TX_FAILURE",

  GETSINGLE_TX_REQUEST: "GETSINGLE_TX_REQUEST",
  GETSINGLE_TX_SUCCESS: "GETSINGLE_TX_SUCCESS",
  GETSINGLE_TX_FAILURE: "GETSINGLE_TX_FAILURE",

  GETSINGLE_ORDER_REQUEST: "GETSINGLE_ORDER_REQUEST",
  GETSINGLE_ORDER_SUCCESS: "GETSINGLE_ORDER_SUCCESS",
  GETSINGLE_ORDER_FAILURE: "GETSINGLE_ORDER_FAILURE",

  CREATE_ORDER_REQUEST: "CREATE_ORDER_REQUEST",
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILURE: "CREATE_ORDER_FAILURE",

  TRACK_ORDER_REQUEST: "TRACK_ORDER_REQUEST",
  TRACK_ORDER_SUCCESS: "TRACK_ORDER_SUCCESS",
  TRACK_ORDER_FAILURE: "TRACK_ORDER_FAILURE",

  SEND_TX_HASH_REQUEST: "SEND_TX_HASH_REQUEST",
  SEND_TX_HASH_SUCCESS: "SEND_TX_HASH_SUCCESS",
  SEND_TX_HASH_FAILURE: "SEND_TX_HASH_FAILURE",

  SEND_TX_PROPOSED_REQUEST: "SEND_TX_PROPOSED_REQUEST",
  SEND_TX_PROPOSED_SUCCESS: "SEND_TX_PROPOSED_SUCCESS",
  SEND_TX_PROPOSED_FAILURE: "SEND_TX_PROPOSED_FAILURE",

  GETALL_PROPOSED_TX_REQUEST: "GETALL_PROPOSED_TX_REQUEST",
  GETALL_PROPOSED_TX_SUCCESS: "GETALL_PROPOSED_TX_SUCCESS",
  GETALL_PROPOSED_TX_FAILURE: "GETALL_PROPOSED_TX_FAILURE",

  GETALL_COLLECTED_TX_REQUEST: "GETALL_COLLECTED_TX_REQUEST",
  GETALL_COLLECTED_TX_SUCCESS: "GETALL_COLLECTED_TX_SUCCESS",
  GETALL_COLLECTED_TX_FAILURE: "GETALL_COLLECTED_TX_FAILURE",

  VALIDATE_CODE_REQUEST: "VALIDATE_CODE_REQUEST",
  VALIDATE_CODE_SUCCESS: "VALIDATE_CODE_SUCCESS",
  VALIDATE_CODE_FAILURE: "VALIDATE_CODE_FAILURE",
};
