export const tempDataConstants = {
    ADD_DATA_TO_STORE: 'ADD_DATA_TO_STORE',
    DELETE_DATA_FROM_STORE: 'DELETE_DATA_FROM_STORE',
    ADD_WALLET_DETAILS: 'ADD_WALLET_DETAILS',
    GET_TX_STATUS: "GET_TX_STATUS"
}