export const tokenConstants = {

  GETALLADMIN_TOKEN_REQUEST: 'GETALLADMIN_TOKEN_REQUEST',
  GETALLADMIN_TOKEN_SUCCESS: 'GETALLADMIN_TOKEN_SUCCESS',
  GETALLADMIN_TOKEN_FAILURE: 'GETALLADMIN_TOKEN_FAILURE',

  GETSINGLEADMIN_TOKEN_REQUEST: 'GETSINGLEADMIN_TOKEN_REQUEST',
  GETSINGLEADMIN_TOKEN_SUCCESS: 'GETSINGLEADMIN_TOKEN_SUCCESS',
  GETSINGLEADMIN_TOKEN_FAILURE: 'GETSINGLEADMIN_TOKEN_FAILURE',

  GETSINGLEADMINREPLICA_TOKEN_REQUEST: 'GETSINGLEADMINREPLICA_TOKEN_REQUEST',
  GETSINGLEADMINREPLICA_TOKEN_SUCCESS: 'GETSINGLEADMINREPLICA_TOKEN_SUCCESS',
  GETSINGLEADMINREPLICA_TOKEN_FAILURE: 'GETSINGLEADMINREPLICA_TOKEN_FAILURE',

  GETPROPOSED_TOKEN_REQUEST: 'GETPROPOSED_TOKEN_REQUEST',
  GETPROPOSED_TOKEN_SUCCESS: 'GETPROPOSED_TOKEN_SUCCESS',
  GETPROPOSED_TOKEN_FAILURE: 'GETPROPOSED_TOKEN_FAILURE',

  GETALLREPLICAS_TOKEN_REQUEST: 'GETALLREPLICAS_TOKEN_REQUEST',
  GETALLREPLICAS_TOKEN_SUCCESS: 'GETALLREPLICAS_TOKEN_SUCCESS',
  GETALLREPLICAS_TOKEN_FAILURE: 'GETALLREPLICAS_TOKEN_FAILURE',

  GETSINGLE_TOKEN_REQUEST: 'GETSINGLE_TOKEN_REQUEST',
  GETSINGLE_TOKEN_SUCCESS: 'GETSINGLE_TOKEN_SUCCESS',
  GETSINGLE_TOKEN_FAILURE: 'GETSINGLE_TOKEN_FAILURE',

  GETSINGLE_REPLICA_REQUEST: 'GETSINGLE_REPLICA_REQUEST',
  GETSINGLE_REPLICA_SUCCESS: 'GETSINGLE_REPLICA_SUCCESS',
  GETSINGLE_REPLICA_FAILURE: 'GETSINGLE_REPLICA_FAILURE',

  GETTRENDING_TOKEN_REQUEST: 'GETTRENDING_TOKEN_REQUEST',
  GETTRENDING_TOKEN_SUCCESS: 'GETTRENDING_TOKEN_SUCCESS',
  GETTRENDING_TOKEN_FAILURE: 'GETTRENDING_TOKEN_FAILURE',

  GETALL_PROPOSED_LIKED_TOKEN_REQUEST: 'GETALL_PROPOSED_LIKED_TOKEN_REQUEST',
  GETALL_PROPOSED_LIKED_TOKEN_SUCCESS: 'GETALL_PROPOSED_LIKED_TOKEN_SUCCESS',
  GETALL_PROPOSED_LIKED_TOKEN_FAILURE: 'GETALL_PROPOSED_LIKED_TOKEN_FAILURE',

  GETALL_ORIGINAL_LIKED_TOKEN_REQUEST: 'GETALL_ORIGINAL_LIKED_TOKEN_REQUEST',
  GETALL_ORIGINAL_LIKED_TOKEN_SUCCESS: 'GETALL_ORIGINAL_LIKED_TOKEN_SUCCESS',
  GETALL_ORIGINAL_LIKED_TOKEN_FAILURE: 'GETALL_ORIGINAL_LIKED_TOKEN_FAILURE',

  GETBYALPHABET_TOKEN_REQUEST: 'GETBYALPHABET_TOKEN_REQUEST',
  GETBYALPHABET_TOKEN_SUCCESS: 'GETBYALPHABET_TOKEN_SUCCESS',
  GETBYALPHABET_TOKEN_FAILURE: 'GETBYALPHABET_TOKEN_FAILURE',

  GETRANDOM_TOKEN_REQUEST: 'GETRANDOM_TOKEN_REQUEST',
  GETRANDOM_TOKEN_SUCCESS: 'GETRANDOM_TOKEN_SUCCESS',
  GETRANDOM_TOKEN_FAILURE: 'GETRANDOM_TOKEN_FAILURE',

  GETORIGINAL_TOKEN_REQUEST: 'GETORIGINAL_TOKEN_REQUEST',
  GETORIGINAL_TOKEN_SUCCESS: 'GETORIGINAL_TOKEN_SUCCESS',
  GETORIGINAL_TOKEN_FAILURE: 'GETORIGINAL_TOKEN_FAILURE',

  CREATE_ORIGINAL_ADMIN_TOKEN_REQUEST: 'CREATE_ORIGINAL_ADMIN_TOKEN_REQUEST',
  CREATE_ORIGINAL_ADMIN_TOKEN_SUCCESS: 'CREATE_ORIGINAL_ADMIN_TOKEN_SUCCESS',
  CREATE_ORIGINAL_ADMIN_TOKEN_FAILURE: 'CREATE_ORIGINAL_ADMIN_TOKEN_FAILURE',

  CREATE_USER_ORIGINAL_FROM_ORIGINAL_REQUEST: 'CREATE_USER_ORIGINAL_FROM_ORIGINAL_REQUEST',
  CREATE_USER_ORIGINAL_FROM_ORIGINAL_SUCCESS: 'CREATE_USER_ORIGINAL_FROM_ORIGINAL_SUCCESS',
  CREATE_USER_ORIGINAL_FROM_ORIGINAL_FAILURE: 'CREATE_USER_ORIGINAL_FROM_ORIGINAL_FAILURE',

  CREATE_PROPOSED_TOKEN_REQUEST: 'CREATE_PROPOSED_TOKEN_REQUEST',
  CREATE_PROPOSED_TOKEN_FAILURE: 'CREATE_PROPOSED_TOKEN_FAILURE',
  CREATE_PROPOSED_TOKEN_SUCCESS: 'CREATE_PROPOSED_TOKEN_SUCCESS',

  CREATE_REPLICA_REQUEST: 'CREATE_REPLICA_REQUEST',
  CREATE_REPLICA_SUCCESS: 'CREATE_REPLICA_SUCCESS',
  CREATE_REPLICA_FAILURE: 'CREATE_REPLICA_FAILURE',


  // CREATE_TOKEN_REQUEST: 'CREATE_TOKEN_REQUEST',
  // CREATE_TOKEN_SUCCESS: 'CREATE_TOKEN_SUCCESS',
  // CREATE_TOKEN_FAILURE: 'CREATE_TOKEN_FAILURE',

  // CREATEREPLICA_TOKEN_REQUEST: 'CREATEREPLICA_TOKEN_REQUEST',
  // CREATEREPLICA_TOKEN_SUCCESS: 'CREATEREPLICA_TOKEN_SUCCESS',
  // CREATEREPLICA_TOKEN_FAILURE: 'CREATEREPLICA_TOKEN_FAILURE',


  SEARCH_TOKEN_REQUEST: 'SEARCH_TOKEN_REQUEST',
  SEARCH_TOKEN_SUCCESS: 'SEARCH_TOKEN_SUCCESS',
  SEARCH_TOKEN_FAILURE: 'SEARCH_TOKEN_FAILURE',

  CHANGEOWNERSHIP_TOKEN_REQUEST: 'CHANGEOWNERSHIP_TOKEN_REQUEST',
  CHANGEOWNERSHIP_TOKEN_SUCCESS: 'CHANGEOWNERSHIP_TOKEN_SUCCESS',
  CHANGEOWNERSHIP_TOKEN_FAILURE: 'CHANGEOWNERSHIP_TOKEN_FAILURE',

  CHANGEOWNERSHIP_O_TOKEN_REQUEST: 'CHANGEOWNERSHIP_O_TOKEN_REQUEST',
  CHANGEOWNERSHIP_O_TOKEN_SUCCESS: 'CHANGEOWNERSHIP_O_TOKEN_SUCCESS',
  CHANGEOWNERSHIP_O_TOKEN_FAILURE: 'CHANGEOWNERSHIP_O_TOKEN_FAILURE',


  ADDTOFAVORITES_TOKEN_REQUEST: 'ADDTOFAVORITES_TOKEN_REQUEST',
  ADDTOFAVORITES_TOKEN_SUCCESS: 'ADDTOFAVORITES_TOKEN_SUCCESS',
  ADDTOFAVORITES_TOKEN_FAILURE: 'ADDTOFAVORITES_TOKEN_FAILURE',


};
