export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    VERIFY_ADDRESS: "VERIFY_ADDRESS",

    LOGOUT_REQUEST: 'USERS_LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'USERS_LOGOUT_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    REFRESH_TOKEN: "USERS_REFRESH_TOKEN",

    VERIFYEMAIL_REQUEST: 'USERS_VERIFYEMAIL_REQUEST',
    VERIFYEMAIL_SUCCESS: 'USERS_VERIFYEMAIL_SUCCESS',
    VERIFYEMAIL_FAILURE: 'USERS_VERIFYEMAIL_FAILURE',

    RESENDEMAIL_REQUEST: 'USERS_RESENDEMAIL_REQUEST',
    RESENDEMAIL_SUCCESS: 'USERS_RESENDEMAIL_SUCCESS',
    RESENDEMAIL_FAILURE: 'USERS_RESENDEMAIL_FAILURE',

    GETUSER_REQUEST: 'USERS_GETUSER_REQUEST',
    GETUSER_SUCCESS: 'USERS_GETUSER_SUCCESS',
    GETUSER_FAILURE: 'USERS_GETUSER_FAILURE',


    UPDATEUSER_REQUEST: 'USERS_UPDATEUSER_REQUEST',
    UPDATEUSER_SUCCESS: 'USERS_UPDATEUSER_SUCCESS',
    UPDATEUSER_FAILURE: 'USERS_UPDATEUSER_FAILURE',

    UPDATEPASSWORD_REQUEST: 'USERS_UPDATEPASSWORD_REQUEST',
    UPDATEPASSWORD_SUCCESS: 'USERS_UPDATEPASSWORD_SUCCESS',
    UPDATEPASSWORD_FAILURE: 'USERS_UPDATEPASSWORD_FAILURE',

    CREATECART_REQUEST: 'USERS_CREATECART_REQUEST',
    CREATECART_SUCCESS: 'USERS_CREATECART_SUCCESS',
    CREATECART_FAILURE: 'USERS_CREATECART_FAILURE',

    UPDATECART_REQUEST: 'USERS_UPDATECART_REQUEST',
    UPDATECART_SUCCESS: 'USERS_UPDATECART_SUCCESS',
    UPDATECART_FAILURE: 'USERS_UPDATECART_FAILURE',

    GETCART_REQUEST: 'USERS_GETCART_REQUEST',
    GETCART_SUCCESS: 'USERS_GETCART_SUCCESS',
    GETCART_FAILURE: 'USERS_GETCART_FAILURE',

    GETSINGLECARTITEM_REQUEST: 'USERS_GETSINGLECARTITEM_REQUEST',
    GETSINGLECARTITEM_SUCCESS: 'USERS_GETSINGLECARTITEM_SUCCESS',
    GETSINGLECARTITEM_FAILURE: 'USERS_GETSINGLECARTITEM_FAILURE',

    GETETHPRICE_REQUEST: 'USERS_GETETHPRICE_REQUEST',
    GETETHPRICE_SUCCESS: 'USERS_GETETHPRICE_SUCCESS',
    GETETHPRICE_FAILURE: 'USERS_GETETHPRICE_FAILURE',

    UPDATEADDRESS_REQUEST: 'USERS_UPDATEADDRESS_REQUEST',
    UPDATEADDRESS_SUCCESS: 'USERS_UPDATEADDRESS_SUCCESS',
    UPDATEADDRESS_FAILURE: 'USERS_UPDATEADDRESS_FAILURE',

    DELETESINGLECARTITEM_REQUEST: 'USERS_DELETESINGLECARTITEM_REQUEST',
    DELETESINGLECARTITEM_SUCCESS: 'USERS_DELETESINGLECARTITEM_SUCCESS',
    DELETESINGLECARTITEM_FAILURE: 'USERS_DELETESINGLECARTITEM_FAILURE',

    SEND_RESET_MAIL_REQUEST: 'USERS_SEND_RESET_MAIL_REQUEST',
    SEND_RESET_MAIL_SUCCESS: 'USERS_SEND_RESET_MAIL_SUCCESS',
    SEND_RESET_MAIL_FAILURE: 'USERS_SEND_RESET_MAIL_FAILURE',

    RESETPASSWORD_REQUEST: 'USERS_RESETPASSWORD_REQUEST',
    RESETPASSWORD_SUCCESS: 'USERS_RESETPASSWORD_SUCCESS',
    RESETPASSWORD_FAILURE: 'USERS_RESETPASSWORD_FAILURE'
};
