import { makeStyles } from "@mui/styles";

export const useStyles = makeStyles((theme) => ({
  addressDetails: {
    width: "100%",
    height: 200,
    borderRadius: "2em",
    padding: "1em 2em",
    margin: "1em 0",
    boxShadow: theme.palette.boxShadow.main,
  },
  paymentMethod: {
    width: "100%",
    height: 200,
    borderRadius: "2em",
    padding: "1em 2em",
    margin: "1em 0",
    boxShadow: theme.palette.boxShadow.main,
  },
  orderDetails: {
    margin: "1em 0",
    padding: "2em",
    borderRadius: "2em",
    boxShadow: theme.palette.boxShadow.main,
    "& .MuiTypography-body2": {
      color: theme.palette.primary.light,
      fontSize: ".85em",
      fontWeight: "bold",
    },
  },
  productName: {
    color: theme.palette.primary.main,
    textAlign: "left",
    fontWeight: "bold",
  },
  description: {
    fontSize: ".9em",
  },
  inputBasePaper: {
    p: "1px 5px",
    margin: "1em 0 1.5em 0",
    height: "40px",
    display: "flex",
    // alignItems: "center",
    border: "none",
    borderRadius: "3em",
    // borderColor: theme.palette.primary.light,
    boxShadow: "rgba(99, 99, 99, 0.2) 0px 2px 8px 0px",
    "& input": {
      fontFamily: "poppins",
      fontSize: ".875em",
      color: theme.palette.primary.main,
      fontWeight: "bold",
    },
    "& input::placeholder": {
      fontFamily: "poppins",
      fontSize: ".85em",
    },
    "& input:focus": {
      outline: "none",
    },
  },
  inputHandler: {
    width: "75%",
    borderRadius: "3em",
  },
  ETHhandler: {
    borderRadius: "3em",
    width: "25%",
    background: "linear-gradient(to bottom, #d84d22, #cd4022 )",
  },
  divider: {
    backgroundColor: theme.palette.dividerYellow.main,
  },
  finalBtn: {
    display: "flex",
    justifyContent: "center",
    textAlign: "center",
    alignSelf: "center",
    alignContent: "center",
    alignItems: "center",
    margin: "1em auto",
  },
  textField: {
    width: "100%",
    borderRadius: "3em",
    marginLeft: "auto",
    marginRight: "auto",
    paddingBottom: 0,
    marginTop: 0,
    fontWeight: 500,
    "& .css-1nms4el-MuiInputBase-root-MuiOutlinedInput-root": {
      borderRadius: "3em",
      height: "40px",
      fontSize: ".875em",
      color: "inherit",
    },
  },
  spinAgain: {
    fontWeight: "bold",
    color: theme.palette.textGray.main,
    textTransform: "none",
    textDecoration: "",
  },
  metamask: {
    fontWeight: "bold",
    color: "#121212",
    fontSize: "1.2em",
    borderRadius: "2em",
    border: "2px solid",
    width: "100%",
    padding: ".3em 0",
    marginTop: "3em",
    "& :hover": {},
  },

  card: {
    width: "100px",
    height: "120px",
    margin: "1em auto",
  },
  cardMain: {
    width: "100%",
    height: "100%",
    margin: "0px",
    padding: "0px",
    borderRadius: "1em",
    boxShadow: theme.palette.boxShadow.main,
  },
  imageWrapper: {
    background: "#fff",
    borderRadius: "1em",
    width: "100%",
    height: "100%",
    position: "relative",
    "& img": {
      borderRadius: "1.4em 1.4em 0 0",
    },
  },

  price: {
    color: "#707070",
    fontSize: ".75em",
    fontWeight: "bold",
    "& span": {
      color: theme.palette.dividerYellow.main,
      fontSize: ".7em",
    },
  },

  loginbox: {
    padding: "1.5em",
    width: "50vw",
    height: "50vh",
    borderRadius: "20px",
    display: "flex,",
    position: "relative",
    boxSizing: "border-box",
    [theme.breakpoints.down("md")]: {
      width: "100%",
      height: "80%",
      borderRadius: "20px",
      margin: "0 2em",
    },
  },
  headerText: {
    color: theme.palette.textColor.main,
    textAlign: "left",
    fontWeight: "bold",
    // marginBottom: "1em",
    "& h6": {
      fontWeight: "bold",
    },
  },

  submit: {
    width: "50%",
    margin: "1em 0",
    borderRadius: "3em",
    color: "#fff",
    fontWeight: "bold",
    textTransform: "none",
    boxShadow: theme.palette.boxShadow.main,
    background: "linear-gradient(180deg, #E25822, #D94D22, #B22222)",
    "&:hover": {
      color: "#E25822",
      background: "#fffafa",
      boxShadow: "0px 10px 25px #70707026",
      border: "none",
    },
  },
  style: {
    width: "100%",
    height: "100vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "column",
    bgcolor: "transparent",
    [theme.breakpoints.down("md")]: {
      width: "100%",
      height: "100vh",
      margin: "0 2em",
    },
  },
  addressStyle: {
    width: 600,
    bgcolor: "transparent",
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    [theme.breakpoints.down("md")]: {
      width: "100%",
      padding: "2em",
      transform: "none",
      position: "relative",
      top: "0",
      left: "0",
    },
  },
}));
